[[design-factory]]
= 工厂模式

[[design-factory-overview]]
== 概述

工厂模式(Factory Pattern)是 Java 中最常用的设计模式之一.这种类型的设计模式属于创建型模式,它提供了一种创建对象的最佳方式.

在工厂模式中,我们在创建对象时不会对客户端暴露创建逻辑,并且是通过使用一个共同的接口来指向新创建的对象.

定义: 定义一个创建对象的接口,让其子类自己决定实例化哪一个工厂类,工厂模式使其创建过程延迟到子类进行.[DP].

工厂模式分类:

*  简单工厂模式：又称为静态工厂方法模式。简单工厂模式是由一个工厂对象决定创建出哪一种产品类的实例
*  工厂方法：又称为多态工厂（Polymorphic Factory）模式或虚拟构造子（Virtual Constructor）模式
*  抽象工厂(工具箱模式)：又称为工具箱模式（Kit 或 Toolkit）模式

工厂模式的好处:

*  可维护性.只需要改要改之处.
*  可复用性.
*  可扩展性.
*  灵活性好,

工厂模式的适应性:

*  当一个类不知道它所必须创建的类的时候
*  当一个类希望由它的子类来指定它所创建的对象的时候.
*  当类将创建对象的职责委托给多个帮助子类中的某一个.并且你希望将那一个帮助子类是代理者这一信息局部化的时候.

include::FactorySimple.adoc[leveloffset=+1]

include::FactoryMethod.adoc[leveloffset=+1]

include::FactoryAbstract.adoc[leveloffset=+1]

[[design-abstract-factory-summary]]
== 总结

工厂方法模式和抽象工厂模式不好分清楚,他们的区别如下:

* 工厂方法模式:
** 一个抽象产品类,可以派生出多个具体产品类.
** 一个抽象工厂类,可以派生出多个具体工厂类.
** 每个具体工厂类只能创建一个具体产品类的实例.
* 抽象工厂模式:
** 多个抽象产品类,每个抽象产品类可以派生出多个具体产品类.
** 一个抽象工厂类,可以派生出多个具体工厂类.
** 每个具体工厂类可以创建多个具体产品类的实例,也就是创建的是一个产品线下的多个产品.
* 区别:
** 工厂方法模式只有一个抽象产品类,而抽象工厂模式有多个.
** 工厂方法模式的具体工厂类只能创建一个具体产品类的实例,而抽象工厂模式可以创建多个.
** 工厂方法创建 "一种" 产品,他的着重点在于"怎么创建",也就是说如果你开发,你的大量代码很可能围绕着这种产品的构造,初始化这些细节上面.也因为如此,类似的产品之间有很多可以复用的特征,
所以会和模版方法相随.
** 抽象工厂需要创建一些列产品,着重点在于"创建哪些"产品上,也就是说,如果你开发,你的主要任务是划分不同差异的产品线,并且尽量保持每条产品线接口一致,从而可以从同一个抽象工厂继承.
** 对于 java 来说,你能见到的大部分抽象工厂模式都是这样的: --- 它的里面是一堆工厂方法,每个工厂方法返回某种类型的对象.
比如说工厂可以生产鼠标和键盘.那么抽象工厂的实现类(它的某个具体子类)的对象都可以生产鼠标和键盘,但可能工厂 A 生产的是罗技的键盘和鼠标,工厂 B 是微软的.
这样 A 和 B 就是工厂,对应于抽象工厂;每个工厂生产的鼠标和键盘就是产品,对应于工厂方法;用了工厂方法模式,你替换生成键盘的工厂方法,就可以把键盘从罗技换到微软.但是用了抽象工厂模式,你只要换家工厂,就可以同时替换鼠标和键盘一套.如果你要的产品有几十个,当然用抽象工厂模
式一次替换全部最方便(这个工厂会替你用相应的工厂方法)所以说抽象工厂就像工厂,而工厂方法则像是工厂的一种产品生产线.

[[design-abstract-factory-qa]]
== Q&A

工厂模式不就是在不使用 `new` 操作符的情况下，将类实例化的吗？可为什么在具体实现时仍然使用了 `new` 操作符？:: 工厂模式把具体使用 `new` 操作符的细节包装起来。当然，只要程序是用 Java 语言写的，Java 语言的特性在细节里就一定会体现。
有很多 Java 语言中的 API 提供一些返还新的 Java 对象的方法,能否举出两个这样的例子,请问他们是工厂方法模式吗?:: `toString()` 方法会返回一个 String 类型的对象,`clone()` 方法会返回与原对象类型相同的对象.但他们不是工厂方法模式,因为他们不能返还一个抽象类型.客户端事先都知道将要得到什么对象类型。** 换言之，并非每一个返还一个新的对象的方法都是工厂方法模式 **。
工厂方法可不可以返还在另一个对象里实例化的一个对象?:: 不可以,工厂方法是创建型模式.其用意就是对对象创建过程的封装.虽然不一定每一次都返回一个新的对象 ,但是工厂方法所返回的都应该是在工厂角色中被实例化的对象。** 如果一个方法返还的对象是在另外一个对象中实例化的，那么这个方法就不是工厂方法 **。
一个工厂方法必须返还一个新对象。如果返还的不是一个新的对象，就不符合工厂方法模式的描述。这句话对吗？:: 这是不对的，一个工厂方法可以通过登记自己所创建的产品对象来实现循环提供相同的一些产品对象的功能，在享元模式中，就是使用了这种工厂方法模式。** 换言之，一个工厂方法所提供的产品对象不一定每次都是新的。**

[[design-abstract-factory-java]]
== Java 语言中的应用

* 简单工厂模式
** java.text.DateFormat#getDateInstance()
* 工厂方法模式
** java.lang.Class#newInstance()
** java.lang.Integer#valueOf(String) (Boolean, Byte, Character,Short, Long,Float 和 Double 与之类似)
** java.lang.Class#forName()
** java.lang.reflect.Array#newInstance()
** java.lang.reflect.Constructor#newInstance()
* 抽象工厂模式
** java.util.Calendar#getInstance()
** java.util.Arrays#asList()
** java.util.ResourceBundle#getBundle()
** java.net.URL#openConnection()
** java.sql.DriverManager#getConnection()
** java.sql.Connection#createStatement()
** java.sql.Statement#executeQuery()
** java.text.NumberFormat#getInstance()
** java.lang.management.ManagementFactory (所有 getXXX()方法)
** java.nio.charset.Charset#forName()
** javax.xml.parsers.DocumentBuilderFactory#newInstance()
** javax.xml.transform.TransformerFactory#newInstance()
** javax.xml.xpath.XPathFactory#newInstance()

[[design-abstract-factory-expand]]
== 扩展

* 利用反射+工厂模式,可以解决避免分支判断的问题.
* 工厂模式与单例模式,MVC 模式,亨元模式,备忘录模式等的关系与其发挥的作用.

